[2024-03-21T03:05:44.147+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2024-03-21T03:05:41.297278+00:00 [queued]>
[2024-03-21T03:05:44.172+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2024-03-21T03:05:41.297278+00:00 [queued]>
[2024-03-21T03:05:44.173+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-21T03:05:44.215+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): inaccurate> on 2024-03-21 03:05:41.297278+00:00
[2024-03-21T03:05:44.224+0000] {standard_task_runner.py:60} INFO - Started process 161 to run task
[2024-03-21T03:05:44.229+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2024-03-21T03:05:41.297278+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp03qshhu_']
[2024-03-21T03:05:44.235+0000] {standard_task_runner.py:88} INFO - Job 19: Subtask inaccurate
[2024-03-21T03:05:44.335+0000] {task_command.py:423} INFO - Running <TaskInstance: my_dag.inaccurate manual__2024-03-21T03:05:41.297278+00:00 [running]> on host 0bc8edee533b
[2024-03-21T03:05:44.507+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-03-21T03:05:41.297278+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-21T03:05:41.297278+00:00'
[2024-03-21T03:05:44.511+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-21T03:05:44.512+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2024-03-21T03:05:44.531+0000] {subprocess.py:86} INFO - Output:
[2024-03-21T03:05:44.534+0000] {subprocess.py:93} INFO - inaccurate
[2024-03-21T03:05:44.535+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-21T03:05:44.576+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20240321T030541, start_date=20240321T030544, end_date=20240321T030544
[2024-03-21T03:05:44.607+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-21T03:05:44.644+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
